- alias: "Parent Set Brightness"
  trigger:
    - platform: state
      entity_id: input_number.parent_brightness
  action:
    - service: mqtt.publish
      data:
        topic: "home/user/parent/brightness_pref"
        payload: "{{ states('input_number.parent_brightness') }}"

- alias: "Child Set Brightness"
  trigger:
    - platform: state
      entity_id: input_number.child_brightness
  action:
    - service: mqtt.publish
      data:
        topic: "home/user/child/brightness_pref"
        payload: "{{ states('input_number.child_brightness') }}"

- alias: "Guest Set Brightness"
  trigger:
    - platform: state
      entity_id: input_number.guest_brightness
  action:
    - service: mqtt.publish
      data:
        topic: "home/user/guest/brightness_pref"
        payload: "{{ states('input_number.guest_brightness') }}"
